### ISSUE TITLE
More information about the annotation of the EXACT'09 training data

### ISSUE THREAD

**Issue by lancexiang** [skjerns/ISMI#2]
look at https://github.com/skjerns/ISMI/blob/master/assignment_3/assignment_3.ipynb

under the segment `Data` you find a link with the images and annotations

_Originally posted by @skjerns in https://github.com/skjerns/ISMI/issues/1#issuecomment-570566391_

Sorry to bother you again, i download the data by the link in segment `Data` , but i find some problem in there: the annotation is part(10 case) of the challenge EXACT'09, and the annotation is just a part of airway of a patient series, about start from the middle of the airway, can you provide the whole annotation of the EXACT'09 training set, because i want to use the supvised deep learning methodology to try the segmentation of the airway, thanks a lot!

**Comment by skjerns** [comment]
this is all the data we have, sorry.

are you sure the annotatiuons are not inside the original download, you just need to extract it?

maybe you can mail the organizers of the challenge they might help you out.
